---
title: "目標設定例および設定ガイドライン"
author: "Ryo Nakagami"
date: "2025-06-03"
date-modified: "2025-07-28"
categories: [方法論]
listing_category: general-series
comments:
  utterances:
       repo: RyoNakagami/regmonkey-datascience-blog
       label: discussion
       issue-term: title
---

## 目標設定例

:::: {.no-border-top-table}

| 項目                  | 内容記入例                               |
| ------------------- | ----------------------------------- |
| **目標① 事業数値目標** | グローバル事業利益目標（◯◯億円）・店舗売上目標（△△△億円）達成 |
| **達成水準**        | 確定した目標に対する**達成率**で評価する．             |

::::


[評価基準設定例]{.mini-section}

:::: {.no-border-top-table}

| 評価レベル | 達成率条件                    |説明|
| ----- | ------------------------ | -----|
| 評価 1  | 達成率 110%以上               |高業績を達成し，好転を活かした成果|
| 評価 2  | 達成率 105%以上               |目標を超えた成果|
| 評価 3  | 達成率 100%以上               |目標通りの達成|
| 評価 4  | 達成率 90%以上（※Break-even基準） |損益分岐点レベル（最低限の達成）|
| 評価 5  | 達成率 90%未満（※赤字の可能性あり）     |赤字リスクあり，持続可能性のない成果水準と判断|

: {tbl-colwidths="[20,35,45]"}

::::



### Tips

::: {.callout-note}
### Tip 1: 評価1,2は**「簡単には達成できない目標」**として設計する

- 評価1,2は，単なる目標達成ではなく，「チームの工夫」「機会の最大活用」などによって初めて達成できる水準に設計するべき
- ストレッチ目標（Stretch Goal）として取り扱う

:::


::: {.callout-note}
### Tip 2: 評価は**目標達成率**で行う

- 金額そのものではなく，確定目標に対する比率で評価
- 柔軟性を持たせ，実態に応じて評価可能にする
- 絶対金額で設定してしまうと，期中修正が難しくなる

:::

::: {.callout-note}
### Tip 3: 達成水準の考え方を言語化する

- 「なぜその評価レベルを○○％に設定したのか」という**背景や理由を明示する**こと
- 例：評価4（90%）を損益分岐点とした場合、「事業として利益を維持できる最低ラインであるため」といった説明を添える
- 評価1・2の高い目標水準に対しては，「在庫過剰の状況を逆手に取り，特別販促で売上を押し上げた場合の想定水準」など，チャレンジの意味づけを言語化する

:::

::: {.callout-note}
### Tip 4: 状況に応じて目標は期中に修正する

- 目標は，**期初に設定したまま固定する必要はない**
- 個人の生産性評価が目的なので，経済状況の悪化（例：パンデミック，為替変動）や，業績改善の兆し（例：売上回復、販促効果）に応じて、**目標を途中で引き上げ・引き下げること
- 目標修正時には，関係者の合意と透明性のある記録が重要

:::

::: {.callout-note}
### Tip 5: 数値の根拠 or いつの数値を利用したのか記載する

- 目標に用いた金額・数値については，**どのタイミングの、どの資料に基づいた数値か**を明示する
- 例：「2025年4月3日時点売上予算に基づく」などと記載しておくことで，評価時に「前提条件の認識違い」による混乱を防ぐ。
- 複数の候補値が存在する場合もあるので，「なぜこの数値を基準としたか」の**選定理由**も言及することが推奨

:::
