---
title: "ボイル=シャルルの法則の導出"
author: "Ryo Nakagami"
date: "2025-06-02"
date-modified: "2025-06-30"
categories: [熱力学]
listing_category: physics-listings
comments:
  utterances:
       repo: RyoNakagami/regmonkey-datascience-blog
       label: discussion
       issue-term: title
---

## ボイルの法則とシャルルの法則

::: {#thm- .custom_problem .blog-custom-border}
[ボイルの法則]{.def-title}

温度 $T$ が一定のとき，圧力 $p$ と体積 $V$ は反比例する．つまり，

$$
pV = \text{constant}
$$



:::

ある一定の温度 $T$ の下では，

- 圧力 $p$ を上げれば，それに反比例して体積 $V$ は収縮
- 圧力 $p$ を下げれば，それに反比例して体積 $V$ は膨張

::: {#thm- .custom_problem .blog-custom-border}
[シャルルの法則]{.def-title}

圧力 $p$ が一定のとき，温度 $T$ と体積 $V$ は比例する

$$
\frac{V}{T} = \text{constant}
$$

:::

圧力 $p$ が一定のとき

- 温度 $T$ を上げれば，それに比例して体積 $V$ は膨張
- 温度 $T$ を下げれば，それに比例して体積 $V$ は収縮

## ボイル=シャルルの法則
::: {#thm- .custom_problem .blog-custom-border}
[ボイル=シャルルの法則]{.def-title}

ボイルの法則とシャルルの法則が成立するとき，

$$
\frac{pV}{T} = \text{constant}
$$

これをボイル=シャルルの法則と呼ぶ

:::

::: {.callout-note collapse="false" icon=false}
## Proof 1: 単射仮定

ボイルの法則より温度 $T$ が一定のとき $pV = \text{constant}$，つまり

$$
\begin{align}
pV = f(T) \label{eq-base}
\end{align}
$$

同様に，シャルルの法則より

$$
\frac{V}{T} = g(p)
$$

ここで関数 $g(\cdot)$ を単射と仮定すると

$$
h\left(\frac{V}{T}\right) = p
$$

従って，

$$
h\left(\frac{V}{T}\right) = \frac{f(T)}{v} \ \ \forall v, T
$$

ここで，$\displaystyle\frac{V}{T} = x$ とすると

$$
h(x) = \frac{f(T)}{x\cdot T}
$$

LHSは $x$ の関数であることから，

$$
h(x) = \frac{f(T_1)}{x\cdot T_1} = \frac{f(T_2)}{x\cdot T_2}
$$

$\displaystyle \frac{f(T)}{T} = \lambda$(定数) とおくと

$$
h(x) = \frac{\lambda}{x}
$$

従って，$f(T) = \lambda T$. これを \eqref{eq-base} に代入すると

$$
pV = \lambda T
$$

$T > 0$ より


$$
\frac{pV}{T} = \lambda
$$

:::

::: {.callout-note collapse="false" icon=false}
## Proof: 独立変数

ボイルの法則とシャルルの法則より

$$
\begin{align}
pV &= f(T)\\
\frac{V}{T} &= g(p)
\end{align}
$$

これを $V$ について解いて整理すると

$$
\frac{f(T)}{T} = pg(p)
$$

この式において，左辺は温度のみの関数，右辺は圧力のみの関数．圧力と温度は互いに独立しているため，この式が常に成り立つためには，両辺がそれぞれ定数でなければならない．つまり，

$$
\lambda = \frac{f(T)}{T} = pg(p)
$$

従って，

$$
\begin{align}
f(T) &= \lambda T
\end{align}
$$

よって，

$$
\frac{pV}{T} = \lambda
$$

:::

### 物理的現象としてボイル=シャルルの法則を見てみる

<script src="https://cdn.jsdelivr.net/npm/mermaid@11.7.0/dist/mermaid.min.js"></script>

::: {.center-content}

```{mermaid}
sequenceDiagram
    participant A as p₀, V₀, T₀
    participant B as p₁, V', T₀
    participant C as p₁, V₁, T₁
    A->>B: T₀一定<br>p₀V₀=p₁V'
    B->>C: p₁一定<br>V'/T₀ = V₁/T₁
```
:::

まず，$p_0, V_0, T_0$ の１つの熱力学的な系を，温度 $T_0$ のまま圧力を $p_1, V'$ に変化させると，ボイルの法則より

$$
p_0V_0 = p_1V'
$$

つぎに $p_1$ を一定の下，$V_1, T_1$ へ系を変化させると，シャルルの法則より

$$
\frac{V'}{T_0} = \frac{V_1}{T_1}
$$

ここから

$$
V' = T_0\cdot\frac{V_1}{T_1}
$$

よって

$$
\frac{p_0V_0}{T_0} = \frac{p_1V_1}{T_1} = \text{constant}
$$

を得る．

### ボイル=シャルルの法則から理想気体の状態方程式を導く

1 molの気体は 0℃, 1 atm の条件下で気体の種類によらず体積は 22.41 l になります．ここから

$$
\begin{align}
\frac{pV}{T}
  &= \frac{1.013 \times 10^5 \times 22.41 \times 10^{-3}}{273.15}\\
  &\approx 8.31 \text{[J/mol K]}
\end{align}
$$

- $pV$ の単位あh [Pa･m³] = [Nm] = [J] つまり，エネルギーの単位となる

この定数を $R$ とおくと $R \approx 8.31 \text{[J/mol K]}$．この定数 $R$ を[気体定数]{.regmoneky-bold}と呼ぶ．$n$ molの気体に対しては

$$
\frac{pV}{T} = nR
$$

::: {#exm- .custom_problem }
[空気中の分子数]{.def-title}

20℃，1atmの空気 1cm³の質量と，それに含まれる分子数を求めてみます．条件として

- 空気は酸素と窒素が1:4の比率として，1molあたり質量は28.8とする
- アボガドロ数 $N_a = 6.02 \times 10^{23}$

理想気体の状態方程式より

$$
\frac{22.41}{273.15} = \frac{V}{293.15}
$$


従って，$V = 24.05 \text{[l]} = 24.05 \times 10^3 \text{[cm³]}$．1cm³あたり質量は

$$
\frac{28.8}{24.05 \times 10^3 } \approx 1.20 \times 10^{-3} \text{[g/cm³]}
$$

この空気1cm³あたり分子数は

$$
\frac{N_A}{24.05 \times 10^3} \approx 2.50 \times 10^{19} \text{[個/cm³]}
$$


:::
---
