---
title: "指数関数の微分"
author: "Ryo Nakagami"
date: "2025-01-27"
date-modified: last-modified
categories: [解析]
listing_category: math-general
comments:
  utterances:
       repo: RyoNakagami/regmonkey-datascience-blog
       label: discussion
       issue-term: title
---

## 指数関数の微分

底 $a>1$ のとき，

- 指数関数 $y = a^x$ は区間 $-\infty < x < \infty$ において連続かつ単調増大で, $y \in (0, \infty)$
- 対数関数 $y = \log_a x$ は $y = a^x$ の逆関数で，区間 $0 < x < \infty$ において連続かつ単調増大で, $y \in (\infty, \infty)$


::: {#fig-plot .center}
```{python}
#| code-fold: true
import numpy as np
import matplotlib.pyplot as plt

# PARAMS
base = 2
N = 1000 # data points
min_lim = -2
max_lim = 5
x = np.linspace(min_lim, max_lim, N)

# exponential
y_exp = base ** x

# logarithm
y_log = np.log(x[x>0]) / np.log(base) 

# plot
fig, ax = plt.subplots(ncols=1)
ax.plot(x, y_exp, label='$ y = a^x$')
ax.plot(x[x>0], y_log, label='$y = \log_a x$')
ax.plot(x*0.8, x*0.8, label='45 Degree Line', linestyle='--', color='gray')
ax.axhline(0, color='black', linewidth=0.5)
ax.axvline(0, color='black', linewidth=0.5)
ax.set_xlim(min_lim, max_lim)
ax.set_xticks([])
ax.set_yticks([])
ax.text(0, 0, 'O', fontsize=12, ha='right')
ax.text(1, -0.5, '1', fontsize=12, ha='right')
ax.text(0, 1, '1', fontsize=12, ha='right')
ax.set_ylim(min_lim, max_lim)
ax.set_xlabel('$x$')
ax.set_ylabel('$y$')
for spine in ax.spines.values():
    spine.set_visible(False)
ax.legend()

```

指数関数と対数関数
:::

<div class="blog-custom-border">
::: {#thm- .custom_problem }
<br>

任意の $a > 0$ に対して，$y = a^x$ の導関数は 

$$
\frac{d(a^x)}{dx} = a^x\log a
$$

:::

</div>

<!--::: {.callout-note collapse="true" icon=false}-->
::: {.callout-note collapse="false" icon=false}
## Proof

$a > 1$ のケースを考える

$$
\begin{align}
\frac{d(a^x)}{dx}
    &= \lim_{h\to 0}\frac{a^{x+h} - a^x}{h}\\
    &= a^x\lim_{h\to 0}\frac{a^{h} - 1}{h}\label{base-eq}
\end{align}
$$

<strong > &#9654;&nbsp; $h > 0$の場合</strong>

$h > 0$ であるならば，$a^h > 1$．よって

$$
a^h = 1 + \frac{1}{t}
$$

とおくと，$t > 0$．指数関数の連続性より，$h\to 0$ のとき，$a^h\to 1$. 従って，$t\to\infty$．

ここで，$\displaystyle h = \log_a\left(1 + \frac{1}{t}\right)$ より

$$
\begin{align}
\frac{a^{h} - 1}{h}
    & = \frac{1/t}{\log_a\left(1 + \frac{1}{t}\right)}\\
    &= \frac{1}{\log_a\left(1 + \frac{1}{t}\right)^t}
\end{align}
$$


$$
\lim_{t\to\infty}\left(1 + \frac{1}{t}\right)^t = e
$$

対数関数 $\log_a(x)$ は連続関数なので，$h\to 0$ のとき，$\log_a\left(1 + \frac{1}{t}\right)^t\to \log_a e$．従って，

$$
\begin{align}
\lim_{h\to 0}\frac{a^{h} - 1}{h}
    &= \frac{1}{\log_a e}\\
    &= \log a
\end{align}
$$

<strong > &#9654;&nbsp; $h < 0$の場合</strong>

$h = -z$ を満たす $z>0$ を考える．このとき，

$$
\begin{align}
\frac{a^h - 1}{h}
    &= \frac{a^{-z} - 1}{-z}\\
    &= \frac{1 - a^z}{-z}\frac{1}{a^z}\\
    &= \frac{a^z - 1}{z}\frac{1}{a^z}
\end{align}
$$

$z\to 0$ のとき，$a^z \to 1$ なので

$$
\frac{a^h - 1}{h}\to \log a
$$

従って，$a > 1$ のとき，$\displaystyle \frac{d(a^x)}{dx} = a^x \log a$

<strong > &#9654;&nbsp; $0 < a < 1$ の場合 </strong>

\eqref{base-eq} と展開したとき，$h>0$ のとき $a^h < 1$ となるので

$$
a^h = 1 - \frac{1}{t}\qquad(t>0)
$$

指数関数の連続性より, $h\to 0$ のとき，$a^h\to 0$，従って，$t\to\infty$．

$$
\begin{align}
\frac{a^h-1}{h}
    &= \frac{-\frac{1}{t}}{\log_a(1 - \frac{1}{t})}\\
    &= -\frac{1}{\log_a(1 - \frac{1}{t})^{t}}
\end{align}
$$

ここで

$$
\lim_{t\to\infty} (1 - \frac{1}{t})^{t} = \frac{1}{e}
$$

であるので，対数関数の連続性より，$h\to 0$ のとき $h\to\infty$ だから

$$
\log_a\left(1 - \frac{1}{t}\right)^{t}\to \log_a\frac{1}{e} = -\log_a e
$$

従って，

$$
\lim_{h\to 0}\frac{a^h-1}{h} = \log a
$$

$h<0$ の場合も同様に示せるので，以上より

任意の $a > 0$ に対して，$y = a^x$ の導関数は 

$$
\frac{d(a^x)}{dx} = a^x\log a
$$

が成立する．

:::

### 対数微分法を用いた直感的理解

$a > 0$ としたとき，

$$
\log a^x = x\log a
$$

このとき，両辺を $x$ で微分すると

$$
\frac{D(a^x)}{a^x} = \log a
$$

従って，

$$
D(a^x) = a^x\log a
$$

を得る．