---
title: "自分用VSCodeショートカットシート"
author: "Ryo Nakagami"
date: "2024-12-19"
categories: [環境構築]
listing_category: development
comments:
  utterances:
       repo: RyoNakagami/regmonkey-datascience-blog
       label: discussion
       issue-term: title
---

## VSCode Shortcut sheet

::: {.callout-note collapse="false" icon=false}
## General

|**command**|**動作**|**comment**|
|-----------|-------|-----------|
|`F11`|フルスクリーンモード(toggle)||
|`Ctrl` + `K` `Z`|禅モード|集中作業や投影のときに使用, toggle|
|`Ctrl` + `+/-/0`|Editor画面のzoom in/out/reset||
|`Ctrl` + `super` + `R`|VSCodeのReload|フリーズしたときなどに有効|
|`Ctrl` + `super` + `Q`|VSCodeの終了||
|`Ctrl` + `Shift` + `T`|直前閉じたtabを再び開く||
|`Ctrl` + `=`|Editor fontのサイズ拡大||
|`Ctrl` + `-`|Editor fontのサイズ縮小||
|`Ctrl` + `0`|Editor fontのサイズリセット||
|`Ctrl` + `Shift` +` =`|VSCode Window zoom 拡大||
|`Ctrl` + `Shift` +` -`|VSCode Window zoom 縮小||
|`Ctrl` + `Shift` +` 0`|VSCode Window zoom リセット||

: {tbl-colwidths="[25,40, 35]"}
:::


::: {.callout-note collapse="false" icon=false}
## Editing

|**command**|**動作**|**comment**|
|-----------|-------|-----------|
|`Alt` + `↑/↓`|ラインの入れ替え|logit変更に伴う行の順番入れ替えに便利|
|`Ctrl` + `]`|インデントの追加||
|`Ctrl` + `[`|インデントの削除||
|`Ctrl` + `Shift` + `]`|ブロックの展開||
|`Ctrl` + `Shift` + `[`|ブロックの折りたたみ||
|`Ctrl` + `/`|ラインのコメントアウト(Toggle)|言語に合わせてサーソル行のコメントアウト切り替えができる|
|`Ctrl` + `Shift` + `A`|ブロックコメントアウト(Toggle)||
|`Ctrl` + `D`|検索・置換用の文字ブロックが選択される|`Ctrl`+`H/F`と組み合わせて使うと便利|
|`Ctrl` + `H`|置換モード|正規表現モード `Alt + R`, 置換範囲を選択行に限定 `Alt + L`, 一括変換 `Ctrl + Alt + Enter` と組み合わせると便利．２階連続押すと Replace にフォーカスされる．キャンセルは `Esc`|
|`Ctrl` + `L`|現在の行全体を選択|`Ctrl` +`Shift` + `L`と組み合わせると便利|
|`Ctrl` + `W`|開いているファイルを閉じる||
|`Ctrl` + `super` + `I`|サジェスト機能||
|`Ctrl` + `U`|選択範囲の大文字変換|| 
|`Ctrl` + `super` + `U`|選択範囲の小文字変換||
|`Ctrl` + `Shift` + `↑`|現在位置からライン先頭までの選択(selection)||
|`Ctrl` + `Shift` + `↓`|現在位置からライン末尾までの選択(selection)||
|`Ctrl` + `Shift` + `←`|現在位置から現在位置のword block先頭までの選択(selection)||
|`Ctrl` + `Shift` + `→`|現在位置から現在位置のword block末尾までの選択(selection)||

: {tbl-colwidths="[25,40, 35]"}

:::

::: {.callout-note collapse="false" icon=false}
## Editting + Multicursor

|**command**|**動作**|**comment**|
|-----------|-------|-----------|
|`Ctrl` +`Shift` + `L`|選択箇所にマッチする箇所全てにカーソルを展開|キャンセルしたい場合は`Esc`|
|`Alt` +`Shift` + `↑/↓`|マルチカーソルを上下に展開|キャンセルしたい場合は`Esc`| 

: {tbl-colwidths="[25,40, 35]"}

:::

::: {.callout-note collapse="false" icon=false}
## Editing + 移動

|**command**|**動作**|**comment**|
|-----------|-------|-----------|
|`Home`|文頭まで移動||
|`End`|文末まで移動||
|`Ctrl` + `Home`|ファイル先頭まで移動||
|`Ctrl` + `End`|ファイル文末まで移動||
|`Ctrl` + `G`|指定した行まで移動|同僚から「xxx行目見て」って言われたときに便利|
|`Ctrl` + `U`|直前までいたカーソル位置に戻る||
|`Ctrl` + `Shift` + `\`|次の対応する括弧に移動|`array`やMathJax編集中に便利|
|`Ctrl` + `Shift` + `pageup`|編集tab左移動|
|`Ctrl` + `Shift` + `pagedown`|編集tab右移動|
|`Ctrl` + `tab`|編集tabの選択移動． `Ctrl` + `tab` を押し続けて移動先を選択する|
|`Ctrl` + `super` + `→`|Active Editorを右に移動する||
|`Ctrl` + `super` + `←`|Active Editorを左に移動する||

: {tbl-colwidths="[25,40, 35]"}

:::


::: {.callout-note collapse="false" icon=false}
## GitHub Copilot

|**command**|**動作**|**comment**|
|-----------|-------|-----------|
|`Ctrl` + `i`|インラインGitHub Copilotの起動|キャンセルは`Esc`|
|`Ctrl` + `Alt` + `i`|GitHub Copilotの起動(Toggle)||
|`Ctrl` +`Esc`|Copilotプロセスのキャンセル||

: {tbl-colwidths="[25,40, 35]"}

:::


::: {.callout-note collapse="false" icon=false}
## CSV

<strong > &#9654;&nbsp; 条件</strong>

- [Edit CSV](https://marketplace.visualstudio.com/items/?itemName=janisdd.vscode-edit-csv)がinstall済み


|**command**|**動作**|**comment**|
|-----------|-------|-----------|
|`Ctrl` + `Enter`|現在開かれているcsvファイルをtable ui形式で表示|データサイズが重たいものについては使用注意|

: {tbl-colwidths="[25,40, 35]"}

:::