---
title: "いろいろな三角不等式"
author: "Ryo Nakagami"
date: "2025-03-03"
categories: [複素数, 幾何, 線形代数]
listing_category: math-general
comments:
  utterances:
       repo: RyoNakagami/regmonkey-datascience-blog
       label: discussion
       issue-term: title
---



## シュワルツの不等式と三角不等式

<div class="blog-custom-border" style="margin-top: 1rem; margin-bottom: 1rem;">
::: {#thm- .custom_problem }
**: シュワルツの不等式**
<br>

任意の２つのベクトル $\pmb{a}, \pmb{b}$ に対して，


$$
\vert (\pmb{a}, \pmb{b})\vert \leq ||\pmb{a}||\,||\pmb{b}||
$$

等号が成り立つのは $\pmb a = k\pmb b$ または, $\pmb b = k^\prime\pmb a$ が成り立つ場合に限る($k,k^\prime \in \mathbf R$)．

:::

</div>

<!--::: {.callout-note collapse="true" icon=false}-->
::: {.callout-note collapse="false" icon=false}
## Proof

<strong > &#9654;&nbsp; $\pmb b = \pmb 0$ のとき</strong>

$\pmb b = \pmb 0$ のときは等号が成り立つことは自明．

<strong > &#9654;&nbsp; $\pmb b \neq \pmb 0$ のとき</strong>

$\displaystyle k = \frac{(\pmb a, \pmb b)}{||\pmb b||^2}$ とおくと，

$$
\begin{align}
||\pmb a - k\pmb b||^2
    &= ||\pmb a||^2 - 2k(\pmb a, \pmb b) + k^2 ||\pmb b||^2\\
    &= ||\pmb a||^2 - 2\frac{(\pmb a, \pmb b)^2}{||\pmb b||^2} + \frac{(\pmb a, \pmb b)^2}{||\pmb b||^2}\\
    &= ||\pmb a||^2 - \frac{(\pmb a, \pmb b)^2}{||\pmb b||^2}
\end{align}
$$

ここで，$||\pmb a - k\pmb b||^2 \geq 0$ であるので

$$
||\pmb a||^2 \geq \frac{(\pmb a, \pmb b)^2}{||\pmb b||^2}
$$

これを整理すると

$$
||\pmb a||^2||\pmb b||^2 \geq (\pmb a, \pmb b)^2 \Rightarrow ||\pmb a||\,||\pmb b|| \geq |(\pmb a, \pmb b)|
$$

等号成立が成立するとき $||\pmb a - k\pmb b||^2 = 0$ であるので，$\pmb a = k\pmb b$ が必要条件であることがわかります．

<strong > &#9654;&nbsp; $\pmb a = k\pmb b$ の十分条件性 </strong>

$$
\begin{align}
||\pmb a||\,||\pmb b|| 
    &= |k|||\pmb b||\,||\pmb b||\\
    &= |k|||\pmb b||^2
\end{align}
$$

また

$$
\begin{align}
|(\pmb a, \pmb b)|
    &= |k|(\pmb b, \pmb b)\\
    &= |k|||\pmb b||^2
\end{align}
$$

したがって，$|\pmb a||\,||\pmb b|| = |(\pmb a, \pmb b)|$ が成り立つことがわかります．


:::


<div class="blog-custom-border" style="margin-top: 1rem; margin-bottom: 1rem;">
::: {#thm- .custom_problem }
**: シュワルツの不等式と三角不等式**
<br>

任意の２つのベクトル $\pmb{a}, \pmb{b}$ に対して，

$$
||\pmb{a} + \pmb{b}|| \leq ||\pmb{a}||\, ||\pmb{b}||
$$

等号が成り立つのは $\pmb a = k\pmb b, k\geq 0$ または, $\pmb b = k^\prime\pmb a, k^\prime\geq 0$ が成り立つ場合に限る．

:::

</div>

<!--::: {.callout-note collapse="true" icon=false}-->
::: {.callout-note collapse="false" icon=false}
## Proof

シュワルツの不等式を用いると

$$
\begin{align}
||\pmb{a} + \pmb{b}||^2
    &= ||\pmb{a}||^2 + 2(\pmb{a},\pmb{b}) + ||\pmb{b}||^2\\
    &\leq ||\pmb{a}||^2 + 2||\pmb{a}||\,||\pmb{b}|| + ||\pmb{b}||^2\\
    &= (||\pmb{a}|| + ||\pmb{b}||)^2
\end{align}
$$

したがって，

$$
||\pmb{a} + \pmb{b}|| \leq ||\pmb{a}||\, ||\pmb{b}||
$$

等号成立はシュワルツの不等式の等号が成立し，かつ

$$
(\pmb{a},\pmb{b}) \geq 0
$$

が成立するときとなるので， $\pmb a = k\pmb b, k\geq 0$ または, $\pmb b = k^\prime\pmb a, k^\prime\geq 0$ が成り立つ場合に限ることがわかる．

:::



## 複素数と三角不等式

<div class="blog-custom-border" style="margin-top: 1rem; margin-bottom: 1rem;">
::: {#thm- .custom_problem }
<br>

複素平面上に2点 $z = a_1 + b_1i, w = a_2 + b_2i$ をとったとき，次の不等式が成立する

$$
\begin{gather}
\vert z + w \vert \leq \vert z\vert + \vert w \vert\\
\vert z\vert - \vert w \vert \leq \vert z - w \vert
\end{gather}
$$


これを三角不等式と呼ぶ．


:::

</div>



<!--::: {.callout-note collapse="true" icon=false}-->
::: {.callout-note collapse="false" icon=false}
## Proof 1


注意: この証明は平面空間における三角不等式を前提にしているのでトートロジー疑惑が有ります

```{python}
import matplotlib.pyplot as plt
import numpy as np

# Define the complex numbers
alpha1 = 3 + 4j
alpha2 = 5 + 2j
alpha3 = alpha1 + alpha2
alpha4 = alpha1 - alpha2

# Extract the real and imaginary parts
a1_real, a1_imag = alpha1.real, alpha1.imag
a2_real, a2_imag = alpha2.real, alpha2.imag
a3_real, a3_imag = alpha3.real, alpha3.imag
a4_real, a4_imag = alpha4.real, alpha4.imag

# Create the plot
fig, ax = plt.subplots()

# Plot the vectors
ax.quiver(0, 0, a1_real, a1_imag, angles="xy", scale_units="xy", scale=1, color="k")
ax.quiver(0, 0, a2_real, a2_imag, angles="xy", scale_units="xy", scale=1, color="k")
ax.quiver(
    a1_real,
    a1_imag,
    a2_real,
    a2_imag,
    angles="xy",
    scale_units="xy",
    linewidth=1,
    scale=1,
    edgecolor="gray",
    color="gray",
)
ax.quiver(0, 0, a3_real, a3_imag, angles="xy", scale_units="xy", scale=1, color="k")
ax.quiver(0, 0, a4_real, a4_imag, angles="xy", scale_units="xy", scale=1, color="k")
ax.quiver(
    a1_real,
    a1_imag,
    -a2_real,
    -a2_imag,
    angles="xy",
    scale_units="xy",
    linewidth=1,
    scale=1,
    edgecolor="gray",
    color="gray",
)


# add point
ax.text(a1_real, a1_imag * 1.1, "$z$")
ax.text(a2_real, a2_imag, "$w$")
ax.text(a3_real, a3_imag, "$z+w$")
ax.text(a4_real, a4_imag + 0.5, "$z-w$")


# Set the plot limits
ax.set_xlim(a4_real - 1, max(a1_real, a3_real) + 3)
ax.set_ylim(-1, max(a1_imag, a3_imag) + 3)

# Add grid, labels, and legend
ax.grid()
ax.set_aspect("equal")
ax.set_xlabel("Real Part")
ax.set_ylabel("Imaginary Part")

# Add title
ax.set_title("Complex Number Vectors")

# Show the plot
plt.show()
```

原点と $z, z+w$ を頂点とする三角形を考えます．このときそれぞれの辺の長さは
$\vert z\vert, \vert w\vert, \vert z + w\vert$ となります．

三角形の二辺の和は他の１辺の長さより長いので

$$
\vert z + w \vert \leq \vert z\vert + \vert w \vert
$$

が成立する．

同様に$z, z-w$ を頂点とする三角形についても

$$
\vert z \vert \leq \vert z + w \vert + \vert w \vert
$$

が成り立つので，これを整理すると

$$
\vert z\vert - \vert w \vert \leq \vert z - w \vert
$$

:::

<!--::: {.callout-note collapse="true" icon=false}-->
::: {.callout-note collapse="false" icon=false}
## Proof 2

複素数の絶対値と共役複素数の関係より

$$
\begin{align}
\vert  z + w \vert^2
    &= (z + w)(\bar z + \bar w)\\
    &= z\bar z + w\bar w + w\bar z + z\bar w\\
    &= \vert z\vert^2 + \vert w\vert^2 + w \overline z + z \overline w\\
    &= \vert z\vert^2 + \vert w\vert^2 + w \overline z + \overline{\overline z w}\\
    &= \vert z\vert^2 + \vert w\vert^2 + 2\operatorname{Re}w \overline z\\
    &\leq \vert z\vert^2 + \vert w\vert^2 + 2\vert w \overline z\vert\\
    &= \vert z\vert^2 + \vert w\vert^2 + 2\vert w\vert \vert\overline z\vert\\
    &= \vert z\vert^2 + \vert w\vert^2 + 2\vert w\vert \vert z\vert\\
    &= (\vert z \vert + \vert w \vert)^2
\end{align}
$$

したがって，

$$
\vert  z + w \vert \leq \vert z \vert + \vert w \vert
$$

:::

<div class="blog-custom-border" style="margin-top: 1rem; margin-bottom: 1rem;">
::: {#thm- .custom_problem }
<br>

$\mathbb C^n$ の任意のベクトル $\pmb a, \pmb b$ に対し，次が成立する

$$
||\pmb a + \pmb b|| \leq ||\pmb a|| + ||\pmb b||
$$

:::

</div>

<!--::: {.callout-note collapse="true" icon=false}-->
::: {.callout-note collapse="false" icon=false}
## Proof

$$
\begin{align}
||\pmb a + \pmb b||^2
    &= (\pmb a + \pmb b, \pmb a + \pmb b)\\
    &= ||\pmb a||^2 + ||\pmb b||^2 + (\pmb a, \pmb b) + (\pmb b, \pmb a)
\end{align}
$$

ここでシュワルツの不等式より

$$
\begin{align}
|(\pmb a, \pmb b)| &\leq ||\pmb a||\,||\pmb b||\\
|(\pmb b, \pmb a)| &\leq ||\pmb b||\,||\pmb a|| = ||\pmb a||\,||\pmb b||
\end{align}
$$

従って，

$$
\begin{align}
||\pmb a||^2 + ||\pmb b||^2 + (\pmb a, \pmb b) + (\pmb b, \pmb a)
    &\leq ||\pmb a||^2 + ||\pmb b||^2  + 2 ||\pmb a||\,||\pmb b||\\
    &= (||\pmb a|| + ||\pmb b||)^2
\end{align}
$$

よって，

$$
\begin{gather}
||\pmb a + \pmb b||^2 \leq (||\pmb a|| + ||\pmb b||)^2\\
\Rightarrow ||\pmb a + \pmb b|| \leq ||\pmb a|| + ||\pmb b||
\end{gather}
$$

:::