---
title: "地図と標準誤差"
author: "Ryo Nakagami"
date: "2025-04-01"
date-modified: "2025-07-23"
categories: [統計, 地図]
listing_category: general-series
comments:
  utterances:
       repo: RyoNakagami/regmonkey-datascience-blog
       label: discussion
       issue-term: title
---

## ボーリング調査でトンネル貫通

::: {.callout-note}
## 事実

2019年7月11日に午前10時25分ごろ，長崎発博多行きの特急「かもめ16号」が，トンネルの天井を貫通した掘削機に接触．
異音を聞いた乗務員が列車を緊急停車させ，先頭車両の前面左側などに損傷があるのを確認した．

:::

上記の[事故原因]((./press20190724-1.pdf))としてに鉄道・運輸機構から以下のように発表されています

1. ボーリング工事発注の際に国土地理院の地図（2万5千分の1地形図）に基づき作成した発注図面において JR 長崎本線長崎トンネルの位置が、実際の位置と異なっていた．
2. 長崎トンネルとボーリング工事の位置が図面上で約 80ｍ離れていたため，ボーリング工事による長崎トンネルへの影響はないものと判断し，ボーリング工事前に現地で十分な確認を行っていなかった

### 80m の誤差の程度

「図面上で約 80ｍ離れていた」とありますが，2万5千分の1地形図だと80mのずれは髪の紙面上で

```{python}
#| code-fold: show

error_mm = 80 / 25000 * 1000
print(f"{error_mm} mm誤差")
```

となります．また，国土地理院の地理院地図では，建物の形状が見える地図の拡大率における水平精度は原則として「17.5m(標準誤差)」となっており，地図が現実世界のすべてを精確に表現している訳ではありません．
そのため，

|理由|コメント|
|----|------|
|ボーリング工事発注の際に国土地理院の地図（2万5千分の1地形図）に基づき作成した発注図面において JR 長崎本線長崎トンネルの位置が、実際の位置と異なっていた．|実際の位置と異なるのは想定の範囲内であるべき|
|長崎トンネルとボーリング工事の位置が図面上で約 80ｍ離れていたため，ボーリング工事による長崎トンネルへの影響はないものと判断し，ボーリング工事前に現地で十分な確認を行っていなかった|2万5千分の1地形図のような中縮尺地図で，構造物の精確な位置を判断するのが間違っている|
: {tbl-colwidths="[70,30]"}

と考えるべきだと思います．

References
----------
- [報道発表資料 JR 長崎本線長崎トンネル内で発生させた重大事故（渇水対策を目的とした試掘ボーリングによる走行車両との接触）の原因と対策について](./press20190724-1.pdf)
