---
title: "ある慣性系で２つの平行な軌道"
author: "Ryo Nakagami"
date: "2025-07-01"
date-modified: "2025-07-02"
categories: [線形代数, physics]
listing_category: physics-exercise-listings
comments:
  utterances:
       repo: RyoNakagami/regmonkey-datascience-blog
       label: discussion
       issue-term: title
---

## 慣性の法則と慣性系

::: {#def- .custom_problem .blog-custom-border}
[慣性の法則]{.def-title}

- 質点が何の力も受けないとき，その質点は静止たままか，一定の速度で運動する
- 運動の第一法則とも呼ぶ

:::

慣性の法則が成り立つ座標系を[慣性系]{.regmonkey-bold}といいます．ある座標系が慣性系であれば，それに対して静止しているか等速直線運動をする座標系はすべて慣性系です．

## Exercise

::: {#exr- .custom_problem .blog-custom-border}
<br>

非相対論的(=ニュートン力学で十分に正確に記述できる)な一定の速さで運動する２つの物体の軌道を，ある慣性系で観測したところ平行だった．

a. 別の関係性を選んで，その系では２つの軌道が互いに交差するというのはあり得るか？
b. (a)を満たす座標系があったとして，適当な初期条件のもとに物体が動き始めて，それらが同時に交差する点へ到達することはあり得るか？

:::

::: {.callout-note collapse="false" icon=false}
## Solution (a)

もとの座標系 $K$ で，２つの物体の速度ベクトルを $\pmb{v}_1, \pmb{v}_2$ とする．これらは仮定より平行なので

$$
\pmb{v}_1\times\pmb{v}_2 = \pmb{0}
$$

$K$ に対して，速度 $\pmb v_0$ で動いている座標系 $K^\prime$ で，２つの軌道が互いに交差するならば

$$
\begin{align}
(\pmb v_1 - \pmb v_0) \times (\pmb v_2 - \pmb v_0)
  &= (\pmb v_1 - \pmb v_2) \times \pmb v_0\\
  &\neq \pmb{0}
\end{align}
$$

この条件が満たされるには

- 2つの $\pmb{v}_1, \pmb{v}_2$ の速度の大きさが異なっている
- 2つの $\pmb{v}_1, \pmb{v}_2$ の速度差ベクトルが $\pmb{v}_0$ と平行ではない

が必要となります．

:::

::: {.callout-note collapse="false" icon=false}
## Solution (b)

物体１の $t=0$ における位置を座標系 $K$ の原点にとると，時刻 $t$ における２つの物体の位置ベクトルは，$t=0$ における２つの物体の相対位置ベクトルを $\pmb{d}$ とすると

$$
\begin{align}
\pmb{r}_1(t) &= \pmb{v}_1t\\
\pmb{r}_2(t) &= \pmb{v}_2t + \pmb{d}
\end{align}
$$

これを座標 $K^\prime$ での位置ベクトルになおすと

$$
\begin{align}
\pmb{r}_1^\prime(t) &= (\pmb{v}_1 - \pmb{v}_0)t\\
\pmb{r}_2^\prime(t) &= (\pmb{v}_2 - \pmb{v}_0)t + \pmb{d}
\end{align}
$$

もし２つの物体が時刻 $t_0$ にある点で出会うならば

$$
\pmb{r}_1^\prime(t_0) = \pmb{r}_2^\prime(t_0)
$$

つまり，

$$
(\pmb{v}_1 - \pmb{v}_2) t_0 = \pmb{d}
$$

この条件が満たされるには

- $\pmb{d}$ が２つの物体の軌道に平行であればよい

つまり，物体２の出発地点が物体１の直線経路上にあれば良いことになります．言い換えると，座標系 $K^\prime$ で観測したときに，
２つの物体が同じ時刻に同じ場所にいるとすれば，座標系 $K$ で観測しても，同じように出会うはずである．

:::


Refereneces
-----------
- [ベクトル空間における外積](../2025-04-09-vector-outer-product/index.html)
