---
title: "収束の条件とCauchyの判定法"
author: "Ryo Nakagami"
date: "2025-07-02"
date-modified: "2025-07-13"
categories: [解析, 収束]
listing_category: math-general
comments:
  utterances:
       repo: RyoNakagami/regmonkey-datascience-blog
       label: discussion
       issue-term: title
---

## 区間縮小法

::: {#thm- .custom_problem  .blog-custom-border}
[区間縮小法]{.def-title}

閉区間 $I_n = [a_n, b_n] \, \ (n=1,2,\cdots)$ において，

1. 各区間 $I_n$ がその前の区間 $I_{n-1}$ に含まれ
2. $n$ が限りなく増すとき，区間 $I_n$ の幅 $b_n - a_n$ が限りなく小さくなる
3. 任意の $m, n$ に対して，$a_n < b_m$

とき，これらの各区間に共通なるただ一つの点が存在する(=各区間に共通なる数が唯一つ確定する)

:::

::: {.callout-note collapse="false" icon=false}
## Proof

仮定 1, 3 より

$$
a_1 \leq a_2 \leq \cdots a_n \leq \cdots b_n \leq \cdots b_2 \leq b_1
$$

数列 $\{a_n\}, \{b_n\}$ は有界かつ単調増加/減少であるので，

$$
\lim_{n\to\infty}a_n = \alpha, \lim_{n\to\infty}b_n = \beta
$$

任意の $m, n$ に対して，$a_n < b_m$ であるので，

$$
\begin{align}
n\to\infty &\Rightarrow \alpha \leq b_m\\
m\to\infty &\Rightarrow \alpha \leq \beta
\end{align}
$$

また, 仮定 2 より，任意の $\epsilon > 0$ に対応して

$$
b_n - a_n < \epsilon
$$

を満たす $n$ が存在し，

$$
a_n \leq \alpha \leq \beta \leq b_n
$$

従って，

$$
0 \leq \beta - \alpha < \epsilon
$$

任意の $\epsilon >0$ について成立するので

$$
\alpha = \beta
$$


:::

### 区間縮小法からDedekindの定理の導出

::: {#thm- .custom_problem  .blog-custom-border}
[Dedekindの定理]{.def-title}

実数の切断 $(A, B)$ が与えられたとき，ただ１つの数 $s$ が存在し，$s$ は Aの最大数 xor Bの最小数である．

:::

::: {.callout-note collapse="false" icon=false}
## Proof: 区間縮小法を用いた証明

$A, N$ から一対の数 $a, b$ を取り出して，区間 $I_0 = [a, b]$ を定義します．

$$
\frac{a+b}{2}
$$


は中間の数なので，A または B のどちらか一方に属していなければなりません．この条件に応じて

$$
\begin{align}
\frac{a+b}{2} \in A &\Rightarrow a_1 = \frac{a+b}{2}, b_1 = b\\
\frac{a+b}{2} \in B &\Rightarrow a_1 = a, b_1 = \frac{a+b}{2}
\end{align}
$$

として区間を更新していきます．

区間が更新されるたびに

$$
\begin{align}
I_0\text{の幅} &= b-a\\
I_1\text{の幅} &= \frac{b-a}{2}\\
I_2\text{の幅} &= \frac{b-a}{4}\\
\vdots &\\
I_n\text{の幅} &= \frac{b-a}{2^n}
\end{align}
$$

となるので，

$$
I_1 \supset I_2 \supset \cdots \supset I_n \supset \cdots
$$

従って，各区間に共通する数はただ１つ $s$ と定まり，それは切断 $(A, B)$ の上組または下組の属す必要があります．

$s\in A$ とすると，任意の $s^\prime > s$ は $b_n \to s$ より

$$
s < b_n < s^\prime \text{なる $b_n$ が存在する} \Rightarrow s^\prime \in B
$$

つまり，$s$ は $A$ の最大数であり，このとき $B$ には最小数は存在しません．仮に，$s^\prime$ を $B$ の最小数とすると

$$
s_0 = \frac{s^\prime - s}{2}
$$

なる数を考えると，十分大きな$n$ について任意の$\epsilon > 0$ で

$$
|b_n - s| < \epsilon\Rightarrow |b_n - s| < \frac{s^\prime - s}{4}
$$

を満たすような $b_n$ が考えられ，このとき $b_n < s^\prime$ であるので，最小数の仮定と矛盾します．


もしも，$s\in B$ であるならば，同様のロジックで $s = \min(B)$ であり，$A$ の最大数は存在しないことになります．

:::

## Cauchyの判定法

::: {#thm- .custom_problem  .blog-custom-border}
[Cauchyの判定法]{.def-title}

数列 $\{a_n\}$ が収束するために必要かつ十分なる条件は，任意の $\epsilon > 0$ に対応して $n_0$ が定められて，

$$
p > n_0, q > n_0 \Rightarrow |a_p - a_q| < \epsilon
$$

:::

::: {.callout-note collapse="false" icon=false}
## Proof: 高木解析概論 p12 より

[必要条件]{.mini-section}

$a_n \to \lambda$ であるならば収束の定義より，ある $N(\epsilon)$ が存在して

$$
p > N(\epsilon), q > N(\epsilon) \Rightarrow |a_p - \lambda| <\frac{\epsilon}{2}, |a_q - \lambda| <\frac{\epsilon}{2}
$$

従って，

$$
\begin{align}
|a_p - a_q| 
  &= |a_p - \lambda + \lambda  - a_q|\\
  &\leq |a_p - \lambda| + |a_q - \lambda| \,\ \because{\text{三角不等式}}\\
  & < \epsilon
\end{align}
$$

よって，収束列はコーシー列です．


[十分性]{.mini-section}

${a_n}$ がコーシー列であるとする：

条件より以下のように ${a_n}$ は有界となります．

$$
p > n_0 \Rightarrow |a_p - a_{n_0 + 1}| < \epsilon, \, \ \text{$n_0$ は確定なので有限個の数列 $\{a_n\}_{n=1}^{n_0}$ を加えても有界}
$$

次に，任意の $n$ について，$\{a_k\}_{k=n}^\infty$ を対応させて，その数列に対応する上限と下限を $l_n, m_n$ として，

$$
I_n = [m_n, l_n]
$$

とおくと，

$$
\begin{gather}
m_1 \leq m_2 \leq \cdots \leq m_n \leq \cdots l_n \leq \cdots l_2 \leq l_1\\
I_1 \supset I_2 \supset \cdots \supset I_n \supset \cdots
\end{gather}
$$

ここで改めて，任意の $\epsilon > 0$ に対応して $n_0$ が定められて，

$$
p > n_0,  q > n_0 \Rightarrow |a_p - a_q| < \epsilon
$$

$n > n_0$ とすると，上限の定義より任意の $q \geq n$ に対して

$$
l_n - a_q < \epsilon
$$

また，下限の定義より，

$$
a_q - m_n < \epsilon
$$

であるので，

$$
l_n - m_n \leq 2\epsilon
$$

$\epsilon > 0$ は任意なので、区間 $I_{n}$ の長さ $l_{n} - m_{n}$ は $0$ に収束し．

$$
l_n \to \lambda, m_n \to \lambda \, \, \because{\text{区間縮小法}}
$$

となるような $\lambda$ が存在します．これは，$a_n \to \lambda$ を意味します．実際，十分大きな $n$ について

$$
|a_n - \lambda| \leq l_n - m_n \leq \epsilon
$$

が成立します．

:::

### 無限級数の収束とCauchyの判定法

::: {#def- .custom_problem .blog-custom-border}
[無限級数の収束]{.def-title}

数列 $\{a_n\}$ の最初の $n$ 項の和を

$$
s_n = a_1 + a_2 + \cdots + a_n
$$

としたとき，$\lim_{n\to\infty}s_n = s$ が存在するならば，無限級数 $\sum_{n=1}^\infty a_n$ は収束するといいます．

:::

Cauchyの判定法により $n$ を十分大きくして，任意の $m > n$ について

$$
|s_n - s_m| = |a_{n+1} + \cdots + a_m| < \epsilon
$$

が $s_n$ の収束の必要十分条件となります．故に収束の場合は，

$$
\lim_{n\to\infty}\sum_{p=1}^\infty a_{n+p} = 0
$$

となります．

[$\lim_{n\to\infty}a_n = 0$ は無限級数収束の必要条件 but not 十分条件]{.mini-section}

Cauchyの収束条件より $n$ を十分大きくしたとき

$$
|s_{n+1} - s_n| < \epsilon \Rightarrow \lim_{n\to\infty} a_n = 0
$$

となりますが，逆は成り立ちません．

例えば

$$
s_n = \sum_{k=1}^n \frac{1}{k}
$$

を考えると，

$$
\lim_{n\to\infty}\frac{1}{n} = 0
$$

は成立しますが，級数についてのCauchy判定条件を見てみると，$n$ を十分大きくしても

$$
|s_{2n} - s_n| = \underbrace{\frac{1}{n+1} +\cdots +\frac{1}{2n}}_{n\text{個}} > \frac{1}{2n} \times n = \frac{1}{2}
$$

となり，条件を満たさないため収束しません．実際にオイラー定数 $\gamma$ を用いると以下のような関係式になります

$$
\sum_{k=1}^n = \ln N + \gamma + \omicron(1)
$$





References
----------
- [定本 解析概論, 高木貞治 著](https://www.iwanami.co.jp/book/b265489.html)
- [数列の極限 Tips](../2025-07-10-limit-operation/index.qmd)