---
title: "[過去記事の転記] Ubuntu Desktop Noble Numbatのインストール"
author: "Ryo Nakagami"
date: "2024-06-07"
date-modified: "2025-12-19"
categories: [環境構築, Ubuntu]
listing_category: development
comments:
  utterances:
       repo: RyoNakagami/regmonkey-datascience-blog
       label: discussion
       issue-term: title
---

::: {.callout-note}
## 目的

- Ubuntu Desktop Noble NumbatをIntel Core i7-9700デスクトップへインストール

:::


## 作業環境情報

[Ubuntu Desktop Noble Numbatインストール先]{.mini-section}

- CPU: Intel Core i7-9700 CPU 3.00 GHz
- Memory: RAM 	32.0 GB
- GPU: NVIDIA GeForce RTX 2060 SUPER

[Ubuntu インストールメディア作成環境]{.mini-section}

- Ubuntu 22.04.4 LTS x86_64 6.5.0-35-generic
- ディスク管理ツール Disks を用いてインストールメディアを作成

## 作業

::: {.callout-note}
### 作業手順

1. Ubuntu Desktop 24.04 LTSのISOファイルのダウンロード (15~20 min)
2. USBインストールメディアの作成 (1~2 min)
3. Ubuntu 24.04 LTSのインストール(20 min)

:::


### 1. Ubuntu ISOファイルのダウンロード

日本のUbuntuミラーサーバーの一つであるTsukuba WIDEの[Ubuntu Desktop 24.04 isoファイルダウンロードリンク](https://ftp.tsukuba.wide.ad.jp/Linux/ubuntu-releases/24.04/)
より isoファイルを取得します．isoファイルサイズは約 6 GBで，ダウンロード時間は15~20分程度(6 MB/sec)程度かかりました．

::: {#def- .custom_problem .blog-custom-border}
[ISOファイル]{.def-title}

- CD-ROMやDVDのディスクイメージ(光ディスク用アーカイブファイル)をそのままファイルにしたもの
- ディスクからコピーした一般的なファイルでは，ヘッダー情報が消失しており完全なデータは含まれないが，ISOファイルにはディスクからのヘッダー情報を含む完全なデータが格納されている

:::

ここで言うヘッダーは ファイルのヘッダーではなく，以下のようなディスクレベルのヘッダー・メタ情報のことです．

- ブートセクタ / EFI System Partition 情報
- パーティションテーブル（MBR / GPT）
- ファイルシステムの管理情報
- ブートローダ配置情報

OSを書き込むときは，対象デバイスには**OSは存在しない**ので，ファイルという概念をデバイスが理解することが出来ません．この段階でできることは
[ディスクの先頭から決められた位置を読む]{.regmonkey-bold}という作業になります．これはBIOS/UEFIによって実行されます．

そのため，起動可能であるためには，ディスク先頭（LBA 0 付近）に起動コードや構造情報が物理配置として存在している必要があります．
なので普通のファイルではなくISOファイルが必要となります．

### 2. USBインストールメディアの作成

::: {#def- .custom_problem .blog-custom-border}
[インストールメディア]{.def-title}

- ISOファイルを実体化したもの
- ISOファイルに格納されたディスクイメージをUSBメモリ上にセクタ単位で書き表し，BIOS / UEFI が直接起動可能な状態にした媒体のこと

:::

ファイルを置いたUSBだけではBIOS/UEFIで読み込むことは出来ないため，ISOファイルを焼いてインストールメディアを作成します．

[手順]{.mini-section}

「Disks」アプリケーションを利用してUSBインストールメディアを作成しました．手順は

1. アプリケーションから「Disks」を立ち上げる
2. 左ペインのDisk一覧からUSBインストールメディアの物理デバイスとなるUSBフラッシュメモリを選択
3. 右上のメニューボタンから `Restore Disk image` を選択
4. `Destination` が意図した物理デバイスかどうか確認
5. `Image to Restore` 項目にて，上でダウンロードしたISOファイルを選択し，`Start Restoring` をクリック

上記手順に従い実行したところ，約2分ほどでインストールメディア作成が完了しました．

### 3. Ubuntu 24.04 LTS インストール

[手順]{.mini-section}

1. USBインストールメディアを差し込んだ状態でUEFI環境経由boot managerを起動
  - HP製なので `esc` + `F10`
2. 起動デバイスを差し込んだUSBフラッシュメモリにする
3. Try to install Ubuntuを選択し，案内通りに作業を行う(約 20 min)
4. Ubuntu Proをenableする

[注意点]{.mini-section}

**インストール言語**

- 基本的に[English]{.regmonkey-bold}を選択すること
- 日本語に変更したい場合は，インストール後に変更すること
- フォントが足りず文字化けが発生するリスクを抑えるため


**インストール先ディスクの選択**

インストーラーは接続されている全ディスクを表示するので，間違ったものを選ばないこと．対策として，

- インストール前に不要な外付けHDD/USBは物理的に抜く
- 事前にディスクサイズや型番を確認する

**ネットワーク接続**

Ubuntu Pro設定や最新アップデートの適用などネットワーク接続舌状態でインストールするほうが便利です．
事前にIPアドレス等を確認しておくことを推奨します．

**ユーサーの設定**

ユーザー名とhostnameもインストール時に設定します．事前にちゃんと考えておきましょう．

:::: {.no-border-top-table}

| 項目                       | 正確な意味                     | 実際に使われる場所                       |
| ------------------------ | ------------------------- | ------------------------------- |
| **Your name**            | 表示名（フルネーム）                | GUIログイン画面，設定画面            |
| **Your computer’s name** | マシンの識別名（hostname）         | ターミナル，SSH，ネットワーク，ログ             |
| **Pick a username**      | Linux内部で使われるユーザー名（ユーザーID） | `/home/username`，sudo，SSH，所有者情報，大文字は使えない |
| **Use Active Directory** | Windowsドメイン（AD）連携設定       | ログイン認証，ユーザー管理                   |

:::

**タイムゾーンの変更**

インストール後に時刻がおかしい場合は，UTCになっている可能性が高いです．

```bash
# 現在のタイムゾーンの確認
timedatectl

# 利用可能なタイムゾーンの確認
timedatectl list-timezones

# ある程度見当がついているなら
timedatectl list-timezones | grep Tokyo

# タイムゾーンの設定
sudo timedatectl set-timezone Asia/Tokyo
```

ただ，システムロケール選択内容に合わせて設定されるので，基本的には心配は不要です

**ホームディレクトリの暗号化**

ハードディスクを取り出して他のパソコンに接続されると，OSを動かすことはできなくてもデータは見られてしまいます．
そのためラップトップの場合は，暗号化したほうが良いと思いますが，デスクトップやサーバーの場合は不要だと思います．

References
----------
- [Ubuntu 24.04.3へのupgrade](https://ryonakagami.github.io/regmonkey-datascience-blog/posts/2025-08-16-ubuntu-upgrade/index.html)
