meta-data:
  repository_name: regmonkey-datascience-blog
  visibility: public
  org-name: RyoNakagami
  homepage: https://ryonakagami.github.io/regmonkey-datascience-blog/
  tag:
    - blog
    - github-pages
    - quarto
    - datascience
  description: |
    A blog about data science topics, including tutorials, tips, and best practices.
  license: mit
