---
title: "ドキュメントを書くにあたってのポイント"
author: "Ryo Nakagami"
date: "2020-03-10"
date-modified: "2026-02-05"
categories: [方法論]
listing_category: general
comments:
  utterances:
       repo: RyoNakagami/regmonkey-datascience-blog
       label: discussion
       issue-term: title
---

::: {.callout-note}
## 問題設定

- 何を書きたいかのアイデアを持っているが，どのように書いたら良いのかわからない

:::


## 基本原則
### 文章を書くまえに考えるべきこと

:::{style="padding-left: 1em"}

- [ ] 文章の目的は何か？
- [ ] 誰に向けて書いているのか？
- [ ] 文章の形式はどのようなものが良いのか？
- [ ] 上記の目的を達成するため，どのようなトーンや言葉を用いて書けば良いのか？

:::

### 文章の基本原則

:::{.space-list-025}

1. Topicと主張 (argument) はIntroductionで明らかにしなくてはならない
2. 読者が今どこにいて，これからどこに行くのか理解できように，mapとsignpostを文章の至る所に掲示するべき（内容を理解させるために必要）
3. 文章は客観的に書かなくてはならない
4. 感情的な文章は避けなくてはならない
5. 結果や議論を述べるときは，慎重にならなくてはならない
6. 読み手が共有している事実，現実を意識した上で文章を書くべき
7. 盗作はダメだが，自分の文章と他の文章との関係性を示すためにReferenceは必ず言及すべき
8. 文章は，文章の種類や読者層の要請からくるお作法に従わなくてはならない
9. conclusionが存在する

:::

## Appendix: LanguageとAcademic writing

- ここではEnglishという自然言語を想定して述べるが，どの言語にも応用ができる。
- この分類はどのような目的を持ってどこをターゲットして勉強するかを明確化するのに役に立つ

```ini
English
├─ EGP (English for General Purposes)
└─ ESP (English for Specific Purposes)
   ├─ EOP (English for Occupational Purposes)
   └─ EAP (English for Academic Purposes)
      ├─ EGAP (English for General Academic Purposes)
      └─ ESAP (English for Specific Academic Purposes)

```

### so, hench?

`so`という単語はacademic writingでは避けた方がよく，代わりに`hence`, `therefore`, and `as a consequence` という語彙を選択することが推奨されている
