on:
  workflow_dispatch:
  push:
    branches: [main]

name: Publish regmonkey_datascience_blog

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Count posts
        id: count
        run: |
          count=$(find posts -type f -name "*.qmd" | wc -l)
          echo "count=$count" >> $GITHUB_OUTPUT

      - name: Generate JSON for Shields.io
        run: |
          mkdir -p badges
          echo "{\"schemaVersion\":1,\"label\":\"posts\",\"message\":\"${{ steps.count.outputs.count }}\",\"color\":\"blue\"}" > badges/posts.json

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install poetry
        uses: abatilo/actions-poetry@v3

      - name: Configure Poetry
        run: poetry config virtualenvs.create false

      - name: Install the project dependencies
        run: poetry install --no-root

      - name: Install CmdStan (Linux, macOS)
        run: |
          python -c "import cmdstanpy; cmdstanpy.install_cmdstan(version='${{ needs.get-cmdstan-version.outputs.version }}', cores=4)"

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
