---
title: "理想気体の全微分"
author: "Ryo Nakagami"
date: "2025-07-03"
date-modified: "2025-07-03"
categories: [解析, 熱力学]
listing_category: math-general
comments:
  utterances:
       repo: RyoNakagami/regmonkey-datascience-blog
       label: discussion
       issue-term: title
---

## 微分可能性

::: {.custom_problem .blog-custom-border}

{{< reveal_vspace 1em >}}

関数 $z = f(x,y)$ を $P = (x, y)$ の近傍において考察します．

$$
\Delta z = f(x + \Delta x, y + \Delta y) - f(x, y)
$$

としたとき，次のように考える

$$
\Delta z = A\Delta x + B\Delta y + \epsilon\rho \label{eq-differential}
$$

このとき，

- $A, B$ は $\Delta x, \Delta y$ には関係しない係数
- $\rho = \sqrt{\Delta x^2 + \Delta y^2}$
- $\epsilon \to 0 \ \ \text{ as} \ \ \rho \to 0$

が成立するならば，関数 $z$ は点 $P$ において微分可能であるといいます．

:::

\eqref{eq-differential} が成り立つならば，$\Delta y = 0$ が成立するとき，

$$
\begin{align}
\rho &= |\Delta x|\\
\frac{\Delta z}{\Delta x} &= A \pm \epsilon
\end{align}
$$

このとき，微分可能性の仮定より $\Delta x \to 0$ と共に $\epsilon \to 0$ だから，点P において

$$
\frac{\partial z}{\partial x} = A
$$

同様に

$$
\frac{\partial z}{\partial y} = B
$$

### 全微分の導入

点 $(x + \Delta x, y + \Delta y)$ が一定の方向から $(x, y)$ に収束するとき，一定方向からなので

$$
\begin{align}
\Delta x &= \rho \cos\alpha\\
\Delta y &= \rho \sin\alpha
\end{align}
$$

と考えることができます．このとき，

$$
\begin{gather}
\frac{\Delta z}{\rho} = A\cos\alpha + B\sin\alpha + \epsilon\\
\lim_{\rho\to 0}\frac{\Delta z}{\rho} = A\cos\alpha + B\sin\alpha = \frac{\partial z}{\partial x} \cos\alpha + \frac{\partial z}{\partial y} \sin\alpha
\end{gather}
$$

つまり，$\rho\to 0$ とするとき，$\Delta z$ などを $dz$ と表記しなおすと

$$
dz = \frac{\partial z}{\partial x} dx + \frac{\partial z}{\partial y} dy
$$

このように，$z$ が微分可能なるとき，$dz$ を $dx, dy$ に関する一次式で表すことを $z$ の全微分とよびます．

### 領域において微分可能

$z = f(x, y)$ がある領域の各店において微分可能であるとき，その領域において微分可能という．その場合，$f(x, y)$ はその領域で連続です．

::: {#thm- .custom_problem .blog-custom-border}
<br>

ある領域で $\displaystyle \frac{\partial z}{\partial x}, \frac{\partial z}{\partial y}$ が存在してかつ連続であるならば，$z$はその領域において微分可能である．

:::
---

::: {.callout-note collapse="false" icon=false}
## Proof

$\Delta x, \Delta y$ をそれぞれ $h, k$ と書けば

$$
\begin{align}
\Delta z
  &= f(x+h, y+k) - f(x, y)\\
  &= \underbrace{f(x + h, y +k) - f(x, y +k)}_{(A)} + \underbrace{f(x, y +k) - f(x, y)}_{(B)}
\end{align}
$$

(A) について，$\displaystyle \frac{\partial z}{\partial x}$ が存在し，連続であるので，$x$ に関して平均値の定理が利用できます．つまり，

$$
f(x + h, y + k) - f(x, y + k) = hf_x(x+ \theta h, y +k), \ \ 0< \theta < 1
$$

仮定より $f_x$ は連続であるので

$$
f_x(x+ \theta h, y +k) = f_x(x, y) + \epsilon
$$

とおけば，$h, k\to 0$ のとき $\epsilon \to 0$.

同様に $y$ について考えると

$$
f(x, y+ k) - f(x, y) = kf_y(x, y) + k\epsilon'
$$

整理すると，

$$
\Delta z = hf_x(x, y) + kf_y(x, y) + h\epsilon + k\epsilon'
$$

$\rho = \sqrt{h^2 + k^2}$  とすると $|h|\leq \rho, |k|\leq \rho$ であるので

$$
h\epsilon + k\epsilon' \leq (|\epsilon| + |\epsilon'|)\rho
$$

従って，

$$
\Delta z = hf_x(x, y) + kf_y(x, y) + o(\rho)
$$

従って，$z$ は微分可能であることがわかります．

:::



## 理想気体の $p,v,T$ の全微分

1molの理想気体の状態方程式は

$$
pv = RT
$$

[$p$ を $v, T$ の関数とする場合]{.mini-section}

$$
p(v, T) = \frac{RT}{v}
$$

として，圧力 $p$ を2つの独立変数 $v, T$ の2変数関数とすると，

$$
\begin{align}
dp &= \left(\frac{\partial p}{\partial v}\right)_T dv + \left(\frac{\partial p}{\partial T}\right)_vdT\\
   &= -\frac{RT}{v^2}dv + \frac{R}{v}dT
\end{align}
$$

[$v$ を $p, T$ の関数とする場合]{.mini-section}

$$
dv = -\frac{RT}{p^2}dp + \frac{R}{p}dT
$$


[$T$ を $p, v$ の関数とする場合]{.mini-section}

$$
dT = \frac{v}{R}dp + \frac{p}{R}dv
$$
